name: GitHub Actions Demo
run-name: ${{ github.sha }} Linux Build 🚀
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.6.2'
          cached: false
      - name: Install library
        run: sudo apt-get install -y libglew-dev libglfw3-dev
      - uses: actions/checkout@v4
      - name: ubuntu-build
        id: build
        run: |
          rm -rf cmake-build-release
          cmake -DCMAKE_BUILD_TYPE=Release -B "./cmake-build-release"
          cmake --build "./cmake-build-release" --config Release --target appTrailNext -j 6
          ls
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: TrailNext
          path: "./cmake-build-release/Release/appTrailNext.exe"