name: Linux Build
run-name: ${{ github.sha }} Linux Build 🚀
on:
  push:
    paths:
      - '*.txt'
      - '*.cpp'
      - '*.qml'
      - '.github/workflows/linux.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.6.2'
      - name: Install library
        run: sudo apt-get install -y libglew-dev libglfw3-dev
      - name: Install Glog
        run: |
          git clone https://github.com/google/glog.git
          rm -rf ./lib/glog
          cd glog
          cmake -S . -B build -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX="../lib/glog"
          cmake --build build
          cmake --build build --target install
      - uses: actions/checkout@v4
      - name: ubuntu-build
        id: build
        run: |
          ls -R
          rm -rf cmake-build-release
          cmake -DCMAKE_BUILD_TYPE=Release -B "./cmake-build-release" -DCMAKE_PREFIX_PATH=/home/runner/work/trailnext/trailnext/glog/install/
          cmake --build "./cmake-build-release" --config Release --target appTrailNext -j 6
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: TrailNext
          path: "./cmake-build-release/appTrailNext"