name: Macos Build
run-name: ${{ github.sha }} Macos Build 🚀
on:
  push:
    paths:
      - '*.txt'
      - '*.cpp'
      - '*.qml'
      - '.github/workflows/macos.yml'
jobs:
  build:
    runs-on: macos-14
    steps:
      - name: prepare env
        run: |
          softwareupdate --all --install --force
          sudo xcode-select --print-path
          sudo xcode-select --switch /Library/Developer/CommandLineTools
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.6.2'
          host: 'mac'
          target: 'desktop'
          arch: 'clang_64'
      - uses: actions/checkout@v4
      - name: macos-build
        id: build
        run: |
          rm -rf cmake-build-release
          cmake -DCMAKE_BUILD_TYPE=Release -B "./cmake-build-release"
          cmake --build "./cmake-build-release" --config Release --target appTrailNext -j 6
          ls -a
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: TrailNext
          path: "./cmake-build-release/appTrailNext"