name: Windows Build
run-name: ${{ github.sha }} Windows Build 🚀
on:
  push:
    paths:
      - '*.txt'
      - '*.cpp'
      - '*.qml'
      - '.github/workflows/windows.yml'
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.6.2'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
      - name: Install Vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          runVcpkgInstall: true
      - name: msvc-build
        id: build
        shell: cmd
        run: |
          rmdir /s/q cmake-build-release
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release "-DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}\vcpkg\scripts\buildsystems\vcpkg.cmake" -Wno-dev
          cmake --build "./cmake-build-release" --config Release --target appTrailNext
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: TrailNext
          path: "./cmake-build-release/Release/appTrailNext.exe"